site_name: CD3 Documentation
site_url: https://oracle-devrel.github.io/cd3-automation-toolkit
repo_name: oracle-devrel/cd3-automation-toolkit
repo_url: https://github.com/oracle-devrel/cd3-automation-toolkit

nav:
  - Overview: 
    - cd3-overview.md
    - Introduction: cd3-overview.md  
    - Architecture: architecture.md   
    - Services Supported: supportedservices.md
    - Excel Templates: excel-templates.md
      
  - Install CD3 :
    - install-cd3.md
    - Prerequisites: prerequisites.md
    - Launch CD3 Container:
      - launch-container.md
      - Resource Manager Stack: launch-from-rmstack.md
      - Manual Container Launch: launch-from-local.md
    - Connect CD3 container to OCI: connect-container-to-oci-tenancy.md

  - Use with CLI: 
    - cd3-cli.md
    - Before You Begin: cd3-cli.md
    - Create in OCI  :
      - greenfield-cli.md
      - Steps: greenfield-cli.md
      - OPA integration: opa-integration.md
      
    - Export from OCI : 
      - nongreenfield-cli.md
      - Steps: nongreenfield-cli.md
      

  - Use with Jenkins:
    - cd3-jenkins.md
    - Before You Begin: cd3-jenkins.md
    - Jenkins Dashboard: jenkinsintro.md
    - Create in OCI : 
      - greenfield-jenkins.md
      - Steps: greenfield-jenkins.md
      - Provision multiple services together: multiple-services-jenkins.md
    - Export from OCI : 
      - nongreenfield-jenkins.md
      - Steps: nongreenfield-jenkins.md
    - Commit Local changes to GIT: sync-cli-jenkins.md
  
  - Must Read:
    - must-read-prerequisites.md
    - Manage Network :  
       - manage-network.md
    - Manage Compute : 
       - manage-compute.md
    - Manage OCI Network Firewall : 
       - manage-firewall.md

  - Additional Features:
    - group-tf-files.md
    - Grouping of Terraform Files: group-tf-files.md
    - Remote Management of Terraform State: remotestate.md
    - OCI Resource Manager Upload: resource-manager-upload.md
    - Support for Additional Attrs: additional-attributes.md
    - CIS Compliance Features: cisfeatures.md
    - CD3 Validator: cd3validator.md
    - Migrate CD3 Jenkins: jobs-migration.md

  - Upgrade CD3:
    - upgrade-toolkit.md
    - Steps to Upgrade Toolkit: upgrade-toolkit.md

  - Troubleshooting:
    - knownbehaviour.md
    - Expected Behaviour: knownbehaviour.md
    - Common Issues: commonissues.md
    - FAQs: faq.md
    
  - External References:
    - learningvideos.md
    - Learning Videos: learningvideos.md
    - Tutorials: tutorials.md

  
# Configuration
theme:
  name: material
  font:
    text: Oracle Sans
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - content.code.copy

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left  
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: oracle
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  logo: images/oci.png
  favicon: images/oci.png  
extra_css:
- stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/oracle-devrel/cd3-automation-toolkit
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/playlist?list=PLPIzp-E1msrbJ3WawXVhzimQnLw5iafcp
  generator: false

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: #
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Mukund
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
plugins:
  - search
  - section-index


copyright: |
  &copy; 2022 <a href=""  target="_blank" rel="noopener">Copyright (c) 2021 Oracle and/or its affiliates.</a>